Relational database readme
Bakalets/python-course-alphabet pull request #3
Opened 2019-04-30 05:25 UTC by Bakalets

2019-04-30 05:30 UTC, Bakalets commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW3-Relational_Database](https://trello.com/c/BlKjA4nX/63-hw3-relationaldatabase)

2019-04-30 14:28 UTC, Kristina970 commented on relational_database/homework.py
> +        VALUES ('Thomas','David','Some Address','London','774','Singapore');
integers можна не брати в лапки

2019-04-30 14:32 UTC, Kristina970 commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
CustomerName але customerID? 
в тебе так назви колонок відображаються?

2019-04-30 14:33 UTC, Kristina970 commented on relational_database/homework.py
> +        cursor.execute("DELETE FROM Customers WHERE customerID = '91';")
а якщо в тебе додастся ще один юзер? то ти не останнього видалиш) 
можеш пліз поправити трохи?

2019-04-30 15:21 UTC, Kristina970 commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
customerID  тип integer тому можна його не барти в лапки

2019-05-01 10:43 UTC, Bakalets commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
За integer понял, спасибо.
А что не так с customerID ?  По заданию нужно в первой записи обновить имя на Джони Деп.
Я переделал запрос, что бы он не просто брал customerID=1 , а минимальный с всех customerID. Так находится первая запись и в ней изменяется имя.

2019-05-01 10:44 UTC, Bakalets commented on relational_database/homework.py
> +        cursor.execute("DELETE FROM Customers WHERE customerID = '91';")
Поправил.

2019-05-01 11:40 UTC, Kristina970 commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
маю на увазі фотмат назви колонок, там все ок, просто цікаво які вони в тебе в базі даних, бо для прикладу в мене всі з маленької букви

2019-05-01 14:18 UTC, Bakalets commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
Только что проверил. В таблицах в пайчарме действительно названия с маленькой буквы.
Я брал названия с примеров с сайта https://www.w3schools.com/sql/  где мы тренинровались.

2019-05-01 14:53 UTC, Kristina970 commented on relational_database/homework.py
> +        cursor.execute("UPDATE Customers SET CustomerName='Johnny Depp' WHERE customerID = '1';")
ага, ну насправді краще називати так як в тебе в базі написано, то по-перше такий обраний неймінг ін конвеншин в проекті по-друге ти точно вказуєш звідки і що взяти.
Не можу скинути якісь пруф лінки для підтвердження свої слів, але якщо на w3school глянути то там чітко назва колонки в базі = назви колонки в кверію

2019-05-02 07:45 UTC, yuriimchg requested changes
привіт
я глянув, домашнє виглядає добре, але в двох завданнях не проходяться тести. 
також є невирішені конфлікти гілок в git - спробуй їх також вирішити, можна після того, як здаси домашнє

2019-05-02 07:45 UTC, yuriimchg commented on objects_and_classes/lection/magic_methods/containers.py
> +>>>>>>> 2c9908d3bb0735a021f5c4588206bf187ae26ff1
в тебе тут невирішений конфлікт є
https://help.github.com/en/articles/resolving-a-merge-conflict-using-the-command-line

2019-05-02 07:45 UTC, yuriimchg commented on objects_and_classes/lection/magic_methods/containers.py
> +>>>>>>> 2c9908d3bb0735a021f5c4588206bf187ae26ff1
і тут

2019-05-02 07:45 UTC, yuriimchg commented on objects_and_classes/lection/magic_methods/containers.py
> +
і тут

2019-05-02 07:45 UTC, yuriimchg commented on objects_and_classes/lection/magic_methods/containers.py
> +=======
звідки вони взагалі взялися?
це ж не домашнє

2019-05-02 07:45 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +import sys
як в тебе в пулреквест для дз з базами даних попало попереднє домашнє?

2019-05-02 07:45 UTC, yuriimchg commented on objects_and_classes/homework/homework.py
> +"""
і як попало наступне?

2019-05-02 07:45 UTC, yuriimchg commented on relational_database/homework.py
> +    cur.execute("""
![image](https://user-images.githubusercontent.com/33547678/57061758-bfe08e80-6cc6-11e9-97b4-60d2216a8491.png)
тут щось не так

2019-05-02 07:45 UTC, yuriimchg commented on relational_database/homework.py
> +    cur.execute("SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID)>10;")
тут падає тест
спробуй відсортувати не по країні, а по ІД)

2019-05-02 19:11 UTC, Bakalets commented on objects_and_classes/lection/magic_methods/containers.py
> +>>>>>>> 2c9908d3bb0735a021f5c4588206bf187ae26ff1
Тест не проходит задание №8 , но оно и не должно проходить. Денис об этом говорил. Там неправильная проверка в тесте.
Остальное проходит нормально
![image](https://user-images.githubusercontent.com/49365489/57100286-357c4700-6d27-11e9-9bd8-38054f3f3744.png)

2019-05-02 19:40 UTC, Bakalets commented on build_in_methods_iterators/homework.py
> +import sys
видимо я что то переделывал у себя на компе, потому дз 2 и дз 3 делал в разных папках, но потом решил все перенести в одну, и видимо после этого всё запушил к себе в репозиторий

2019-05-02 19:45 UTC, Bakalets commented on relational_database/homework.py
> +    cur.execute("""
у меня postgress 11.0  и тип денег настроен на доллар , а не на евро, как других версиях

2019-05-03 05:58 UTC, yuriimchg commented on relational_database/homework.py
> +    cur.execute("""
окей

2019-05-04 09:40 UTC, Bakalets commented on relational_database/homework.py
> +    cur.execute("SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID)>10;")
SELECT COUNT(CustomerID), Country FROM Customers GROUP BY Country HAVING COUNT(CustomerID)>10 ORDER BY COUNT(CustomerID) DESC;
Сделал так, в https://www.w3schools.com  выдаёт такой же резултатьт , как ожидавется в тестах task9.json   , но сам тест не проходит,
А так как было в этом пул риквесте, наоборот проходит.
Посмотри плз, а то что то здесь не так.

2019-05-04 17:11 UTC, merged